[metadata]
name = balderhub-heart
description = balderhub-heart: BalderHub Project for writing tests for devices that interacting with a heart
author = Max Stahlschmidt
long_description = file: README.md
long_description_content_type = text/markdown
url = https://hub.balder.dev/projects/heart
license = MIT
license_files = LICENSE
platforms = unix, linux, osx, cygwin, win32
keywords = test, systemtest, reusable, scenario, junit, balder
classifiers =
    License :: OSI Approved :: MIT License
    Operating System :: MacOS :: MacOS X
    Operating System :: Microsoft :: Windows
    Operating System :: POSIX
    Intended Audience :: Developers
    Programming Language :: Python :: 3
    Programming Language :: Python :: 3 :: Only
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Topic :: Software Development :: Libraries
    Topic :: Software Development :: Testing
    Topic :: Utilities
project_urls =
    Source=https://github.com/balder-dev/balderhub-heart/
    Tracker=https://github.com/balder-dev/balderhub-heart/issues

[options]
packages =
    balderhub.heart
    balderhub.heart.lib
    balderhub.heart.lib.scenario_features
    balderhub.heart.lib.setup_features
    balderhub.heart.lib.utils
    balderhub.heart.lib.utils.optical_simulation
    balderhub.heart.scenarios
    balderhub.heart.setups

install_requires =
    baldertest
python_requires = >=3.9
package_dir =
    =src
setup_requires =
    setuptools
    setuptools-scm>=6.0
zip_safe = no
